// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVjVDWUqj3M-h8CYy4oJ0vjVGCd8I0wo',
    appId: '1:982053562617:android:f380ad3eeb85aaf91a1a28',
    messagingSenderId: '982053562617',
    projectId: 'learnenglishapp-50c96',
    storageBucket: 'learnenglishapp-50c96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABuJomqzZtElmeqU6FhQFvwJfDx5LTKV8',
    appId: '1:982053562617:ios:7a9c8a5945d78db61a1a28',
    messagingSenderId: '982053562617',
    projectId: 'learnenglishapp-50c96',
    storageBucket: 'learnenglishapp-50c96.firebasestorage.app',
    androidClientId: '982053562617-ieesthu9se3dsqagd2v85i3arikccpun.apps.googleusercontent.com',
    iosClientId: '982053562617-0elqbte62pv1m8rpr33stism8lh2sudm.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dhrLnTjkXxSvfbLmCQA_UeT_CaXvLMA',
    appId: '1:982053562617:web:d11b02e2d3f35ea21a1a28',
    messagingSenderId: '982053562617',
    projectId: 'learnenglishapp-50c96',
    authDomain: 'learnenglishapp-50c96.firebaseapp.com',
    storageBucket: 'learnenglishapp-50c96.firebasestorage.app',
  );

}